# Generated by Django 3.1.3 on 2021-08-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20210729_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
