# Generated by Django 3.1.3 on 2021-08-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20210815_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.userstatus', verbose_name='status'),
        ),
    ]
