# Generated by Django 3.1.3 on 2021-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_auto_20210729_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('created', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('term', models.PositiveIntegerField(verbose_name='term')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.PositiveIntegerField(default=0, verbose_name='items quantity'),
        ),
    ]
