# Generated by Django 3.1.3 on 2021-07-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0005_auto_20210729_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='app_goods.item', verbose_name='item'),
        ),
    ]
