# Generated by Django 3.1.3 on 2021-07-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0006_auto_20210729_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_goods.shop', verbose_name='shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_goods.shop', verbose_name='shop'),
            preserve_default=False,
        ),
    ]
