# Generated by Django 3.1.3 on 2021-08-15 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_goods', '0007_auto_20210729_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='score_accrued',
            field=models.BooleanField(default=False, verbose_name='score accrued'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
