# Generated by Django 3.1.3 on 2021-08-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0010_auto_20210815_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.PositiveIntegerField(default=0, verbose_name='items quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.PositiveIntegerField(default=0, verbose_name='items quantity'),
        ),
    ]
