# Generated by Django 3.1.3 on 2021-02-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
