# Generated by Django 3.1.3 on 2021-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0004_auto_20210203_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/02032021-22-29-48_', verbose_name='Файл'),
        ),
    ]
